### ISSUE TITLE
As a user I want to be able to trade resources with other players.

### ISSUE THREAD

**Issue by martinunterhuber** [martinunterhuber/settlers-of-catan#10]
The user can send a trade offer to other players.
The user can accept or decline such offers.

Priority: 60
Story Points: 30

**Comment by edhcvc** [comment]
//TESTCASE
- to check if the player who accepted the offer also gets his ressources in the same time 
- to check if the players ressources will decrease when he sends ressources
- to check if the players ressources will increase when he recieves ressources
