### ISSUE TITLE
As a user I want to be able to cheat/expose a cheater

### ISSUE THREAD

**Issue by martinunterhuber** [martinunterhuber/settlers-of-catan#12]
Possible ways of cheating:
* move the robber
* move a street
* trade resources incorrectly
* ...

Priority: 70
Story Points: 30

**Comment by edhcvc** [comment]
//TESTCASE
- to check if the move of the robber is applied to the game
- to check what happens when you cheat during an saving process
- to check if the game allows you to move a street
- to check if the game allows you to trade incorrectly
