### ISSUE TITLE
As a user i want to be able to choose which colour to play as at the start of the game.

### ISSUE THREAD

**Issue by tilmanni** [martinunterhuber/settlers-of-catan#4]
A user can select from different colours at the start of the game, altough no two players can be the same colour.

Priority: 40
Story Points: 20

**Comment by edhcvc** [comment]
//TESTCASE
- to check what happens when you do not select a colour
- to check if all players are able to select colours at the same time 
- to check which player is the first one to chose a colour - > First come first serve?
